DROP TABLE `activity_logs`;--> statement-breakpoint
DROP TABLE `activity_reviews`;--> statement-breakpoint
DROP TABLE `balance_transactions`;--> statement-breakpoint
DROP TABLE `booking_contacts`;--> statement-breakpoint
DROP TABLE `business_accounts`;--> statement-breakpoint
DROP TABLE `companies`;--> statement-breakpoint
DROP TABLE `company_bookings`;--> statement-breakpoint
DROP TABLE `company_documents`;--> statement-breakpoint
DROP TABLE `company_members`;--> statement-breakpoint
DROP TABLE `company_travelers`;--> statement-breakpoint
DROP TABLE `customer_feedback`;--> statement-breakpoint
DROP TABLE `employees`;--> statement-breakpoint
DROP TABLE `esim_orders`;--> statement-breakpoint
DROP TABLE `generated_documents`;--> statement-breakpoint
DROP TABLE `invoices`;--> statement-breakpoint
DROP TABLE `login_logs`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `stripe_payments`;--> statement-breakpoint
DROP TABLE `top_up_requests`;