CREATE TABLE `company_contracts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int NOT NULL,
	`companyName` varchar(255) NOT NULL,
	`contractNumber` varchar(128) NOT NULL,
	`contractStartDate` date NOT NULL,
	`contractEndDate` date NOT NULL,
	`contractStatus` enum('pending','active','expired','cancelled') NOT NULL DEFAULT 'pending',
	`paymentTerms` enum('prepaid','postpaid','credit') NOT NULL DEFAULT 'prepaid',
	`creditLimit` decimal(12,2) DEFAULT '0.00',
	`discountRate` decimal(5,2) DEFAULT '0.00',
	`commissionRate` decimal(5,2) DEFAULT '0.00',
	`contactPerson` varchar(255),
	`companyEmail` varchar(320),
	`companyPhone` varchar(32),
	`contractFileUrl` varchar(1024),
	`notes` text,
	`createdBy` int,
	`updatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `company_contracts_id` PRIMARY KEY(`id`),
	CONSTRAINT `company_contracts_contractNumber_unique` UNIQUE(`contractNumber`)
);
